### ISSUE TITLE
Robust git

### ISSUE THREAD

**Issue by alexzk1** [savagezen/pkgbuild#9]
In "syncthing", after GIT is clonned, it gets new version, another then manually set and fails to mv folde, suggest changes:

```
folderver=v1.0.0.r29.g1e71b0093
pkgname=syncthing-git
pkgver=${folderver}
```

......

```
build() {
	export GOPATH="${srcdir}"
	cd "${srcdir}"
	mkdir -p "src/github.com/syncthing"
	mv "${pkgname}-${folderver}" "src/github.com/syncthing/${_name}"
```

**Comment by savagezen** [comment]
It should be building normally now.  There were some issues right around the release of v1.0 due to how the versioning worked out in Git pulls.
